CLI/Controller: Use `pipenv` instead of requirements.txt.
Advantages:
  - `pipenv` will manage the virtualenv for you
  - separates dependencies from transient dependencies cleanly
  - just run `pipenv update` to update all dependencies

Disadvantages:
  - it's one more thing

Instructions:
  1. Delete the two *env* directories.
  2. Follow the *README*.

diff --git a/plz b/plz
--- a/plz
+++ b/plz
@@ -1,5 +1,15 @@
 #!/usr/bin/env bash
 
+set -e
+set -u
+
 ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-PYTHONPATH=${ROOT}/cli/src ${ROOT}/cli/env/bin/python ${ROOT}/cli/src/plz/cli/main.py $@
+if ! command -v pipenv > /dev/null; then
+  echo >&2 'Could not find `pipenv`.'
+  exit 2
+fi
+
+PYTHON="$(cd "${ROOT}/cli" && pipenv --venv)/bin/python"
+
+PYTHONPATH="${ROOT}/cli/src" "${PYTHON}" "${ROOT}/cli/src/plz/cli/main.py" "$@"
